import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";
import { gzipSync } from "node:zlib";

const rendererBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const __piImportMeta = {
	get url() {
		const base = process.env.PI_PACKAGE_DIR;
		const filename = base
			? require("node:path").join(base, "main.js")
			: __filename;
		return require("node:url").pathToFileURL(filename).href;
	},
	resolve: (specifier) => require.resolve(specifier),
};
`;

const runtimeBanner = (themeAssets) => `const __piRuntimeImportMeta = {
	url: require("node:url").pathToFileURL(__filename).href,
	resolve: (specifier) => require.resolve(specifier),
};
const __piRuntimeThemeAssets = ${themeAssets};
const __piRuntimeFs = require("node:fs");
const __piRuntimeReadFileSync = __piRuntimeFs.readFileSync;
__piRuntimeFs.readFileSync = function(path, options) {
	const normalized = typeof path === "string" ? path.replace(/\\\\/g, "/") : "";
	const key = normalized.endsWith("/dark.json") ? "dark" : normalized.endsWith("/light.json") ? "light" : "";
	const asset = __piRuntimeThemeAssets[key];
	if (asset !== undefined && normalized.includes("/dist/modes/interactive/theme/")) {
		return typeof options === "string" || options?.encoding ? asset : Buffer.from(asset, "utf8");
	}
	return __piRuntimeReadFileSync.call(this, path, options);
};\n`;

const prod = process.argv[2] === "production";
const pdfWorkerSource = gzipSync(readFileSync("node_modules/pdf-parse/dist/pdf-parse/web/pdf.worker.mjs", "utf8")).toString("base64");
const runtimeThemeAssets = JSON.stringify({
	dark: readFileSync("node_modules/@earendil-works/pi-coding-agent/dist/modes/interactive/theme/dark.json", "utf8"),
	light: readFileSync("node_modules/@earendil-works/pi-coding-agent/dist/modes/interactive/theme/light.json", "utf8"),
});
const nodeExternals = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
	"node:sqlite",
];

// Preact's React-compatibility layer keeps the existing component source and
// produces a small self-contained renderer. In particular, it avoids React
// DOM's dynamic script-element helpers, which community-directory scanning
// correctly flags as unsuitable for a plugin bundle.
const rendererAliases = {
	"react": "preact/compat",
	"react-dom": "preact/compat",
	"react-dom/client": "preact/compat/client",
	"react/jsx-runtime": "preact/jsx-runtime",
};

async function bundleRuntime() {
	const result = await esbuild.build({
		banner: { js: runtimeBanner(runtimeThemeAssets) },
		entryPoints: ["src/runtime/pi-runtime.ts"],
		bundle: true,
		platform: "node",
		define: { "import.meta": "__piRuntimeImportMeta" },
		format: "cjs",
		target: "node22",
		external: nodeExternals,
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		minify: prod,
		write: false,
		outfile: "pi-runtime.cjs",
	});
	const source = result.outputFiles.find((file) => file.path.endsWith("pi-runtime.cjs"))?.text;
	if (!source) throw new Error("Pi runtime bundle was not generated.");
	return gzipSync(source).toString("base64");
}

const runtimeSource = await bundleRuntime();

const rendererContext = await esbuild.context({
	banner: { js: rendererBanner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	alias: rendererAliases,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeExternals,
	],
	define: {
		"import.meta": "__piImportMeta",
		"__PDF_WORKER_GZIP_BASE64__": JSON.stringify(pdfWorkerSource),
		"__PI_RUNTIME_GZIP_BASE64__": JSON.stringify(runtimeSource),
	},
	format: "cjs",
	target: "es2018",
	// Obsidian executes plugins as CommonJS in Electron's renderer. Preserve no
	// dynamic import(): external node:* and Pi provider modules must use require().
	supported: { "dynamic-import": false },
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await rendererContext.rebuild();
	await rendererContext.dispose();
	process.exit(0);
}

await rendererContext.watch();
