import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { cpSync, rmSync, readFileSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
const __piImportMeta = {
	get url() {
		const base = process.env.PI_PACKAGE_DIR;
		const filename = base
			? require("node:path").join(base, "main.js")
			: __filename;
		return require("node:url").pathToFileURL(filename).href;
	},
	resolve: (specifier) => require.resolve(specifier),
};
`;

const prod = (process.argv[2] === "production");
const pdfWorkerSource = readFileSync("node_modules/pdf-parse/dist/pdf-parse/web/pdf.worker.mjs", "utf8");

const rendererContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
		"node:sqlite",
	],
	define: {
		"import.meta": "__piImportMeta",
		"__PDF_WORKER_SOURCE__": JSON.stringify(pdfWorkerSource),
	},
	format: "cjs",
	target: "es2018",
	// Obsidian executes plugins as CommonJS in Electron's renderer. Preserve no
	// dynamic import(): external node:* and Pi provider modules must use require().
	supported: {
		"dynamic-import": false,
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});


const runtimeBanner = `const __piRuntimeImportMeta = {
\turl: require("node:url").pathToFileURL(__filename).href,
\tresolve: (specifier) => require.resolve(specifier),
};\n`;

const runtimeContext = await esbuild.context({
	banner: { js: runtimeBanner },
	entryPoints: ["src/runtime/pi-runtime.ts"],
	bundle: true,
	platform: "node",
	define: { "import.meta": "__piRuntimeImportMeta" },
	format: "cjs",
	target: "node22",
	external: [
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
		"node:sqlite",
	],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "pi-runtime.cjs",
	minify: prod,
});

const copyRuntimeAssets = () => {
	const destination = "runtime-assets/dist/modes/interactive/theme";
	rmSync("runtime-assets", { recursive: true, force: true });
	cpSync("node_modules/@earendil-works/pi-coding-agent/dist/modes/interactive/theme", destination, { recursive: true });
	cpSync("node_modules/pdf-parse/dist/pdf-parse/web/pdf.worker.mjs", "pdf.worker.mjs");
};

if (prod) {
	await rendererContext.rebuild();
	await runtimeContext.rebuild();
	copyRuntimeAssets();
	process.exit(0);
} else {
	await Promise.all([rendererContext.watch(), runtimeContext.watch()]);
}
